sudo: false
env:
  - NODE_VERSION=0.10
  - NODE_VERSION=0.12
  - NODE_VERSION=iojs

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "npm config set spin false"

os:
  - osx
  - linux
script: npm run-script test-all:cover
matrix:
  fast_finish: true

install:
  - test $TRAVIS_OS_NAME = "osx" && brew install nvm && source $(brew --prefix nvm)/nvm.sh || test $TRAVIS_OS_NAME = "linux"
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
  - git --version
  - npm install

addons:
  code_climate:
    repo_token: d349d39a60a008df5ae452af716ad6b8b45d82bf21ff3b60c230af2b34fcc759

after_script:
  - cat coverage/lcov.info | codeclimate
